/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author emmanuelchibua
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        titleLable = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        firstNameTextbox = new javax.swing.JTextField();
        lastNameTextbox = new javax.swing.JTextField();
        dateOfBirthTextbox = new javax.swing.JTextField();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        othersRadio = new javax.swing.JRadioButton();
        maritalStatus = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        workStatus = new javax.swing.JLabel();
        maritalStatusTextbox = new javax.swing.JComboBox<>();
        workStatusTextbox = new javax.swing.JComboBox<>();
        contactInformation = new javax.swing.JLabel();
        town = new javax.swing.JLabel();
        provinces = new javax.swing.JLabel();
        addressTextbox = new javax.swing.JTextField();
        postalCode = new javax.swing.JLabel();
        townTextbox = new javax.swing.JTextField();
        provinceComboBox = new javax.swing.JComboBox<>();
        postalCodeTextbox = new javax.swing.JTextField();
        landMark = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        landMarkTextbox = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        provinces1 = new javax.swing.JLabel();
        emailTextbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleLable.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        titleLable.setForeground(new java.awt.Color(0, 102, 102));
        titleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLable.setText("MEMBERSHIP DATA FORM");

        firstName.setForeground(new java.awt.Color(0, 102, 102));
        firstName.setText("First name");

        lastName.setForeground(new java.awt.Color(0, 102, 102));
        lastName.setText("Last name");

        gender.setForeground(new java.awt.Color(0, 102, 102));
        gender.setText("Gender");

        dateOfBirth.setForeground(new java.awt.Color(0, 102, 102));
        dateOfBirth.setText("Date of birth");

        firstNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextboxActionPerformed(evt);
            }
        });

        dateOfBirthTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthTextboxActionPerformed(evt);
            }
        });

        genderButtonGroup.add(maleRadio);
        maleRadio.setForeground(new java.awt.Color(0, 153, 153));
        maleRadio.setText("Male");
        maleRadio.setActionCommand("MALE USER");
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });

        genderButtonGroup.add(femaleRadio);
        femaleRadio.setForeground(new java.awt.Color(0, 153, 153));
        femaleRadio.setText("Female");
        femaleRadio.setActionCommand("FEMALE USER");

        genderButtonGroup.add(othersRadio);
        othersRadio.setForeground(new java.awt.Color(0, 153, 153));
        othersRadio.setText("Prefer not to say");
        othersRadio.setActionCommand("NOT SPECIFIED");

        maritalStatus.setForeground(new java.awt.Color(0, 102, 102));
        maritalStatus.setText("Marital status");

        address.setForeground(new java.awt.Color(0, 102, 102));
        address.setText("Address");

        workStatus.setForeground(new java.awt.Color(0, 102, 102));
        workStatus.setText("Work status");

        maritalStatusTextbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced" }));
        maritalStatusTextbox.setSelectedIndex(-1);
        maritalStatusTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maritalStatusTextboxActionPerformed(evt);
            }
        });

        workStatusTextbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Employed", "Unemployed" }));
        workStatusTextbox.setSelectedIndex(-1);

        contactInformation.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        contactInformation.setForeground(new java.awt.Color(0, 102, 102));
        contactInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactInformation.setText("Contact Information");

        town.setForeground(new java.awt.Color(0, 102, 102));
        town.setText("Town");

        provinces.setForeground(new java.awt.Color(0, 102, 102));
        provinces.setText("Province");

        addressTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextboxActionPerformed(evt);
            }
        });

        postalCode.setForeground(new java.awt.Color(0, 102, 102));
        postalCode.setText("Postal code");

        townTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townTextboxActionPerformed(evt);
            }
        });

        provinceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan" }));
        provinceComboBox.setSelectedIndex(-1);

        postalCodeTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeTextboxActionPerformed(evt);
            }
        });

        landMark.setForeground(new java.awt.Color(0, 102, 102));
        landMark.setText("Message");

        landMarkTextbox.setColumns(20);
        landMarkTextbox.setRows(5);
        jScrollPane1.setViewportView(landMarkTextbox);

        submit.setForeground(new java.awt.Color(0, 102, 102));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        provinces1.setForeground(new java.awt.Color(0, 102, 102));
        provinces1.setText("Email");

        emailTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(contactInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gender)
                                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateOfBirth)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maritalStatus)
                                        .addComponent(workStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(town, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(provinces, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(landMark, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(provinces1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(33, 33, 33)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(maleRadio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateOfBirthTextbox)
                                    .addComponent(lastNameTextbox, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTextbox, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(femaleRadio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(othersRadio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maritalStatusTextbox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(workStatusTextbox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(townTextbox, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(provinceComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 212, Short.MAX_VALUE)
                                    .addComponent(postalCodeTextbox, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(emailTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName)
                    .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName)
                    .addComponent(lastNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfBirth)
                    .addComponent(dateOfBirthTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender)
                    .addComponent(maleRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(othersRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maritalStatus)
                    .addComponent(maritalStatusTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workStatus)
                    .addComponent(workStatusTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(contactInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinces1)
                    .addComponent(emailTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address)
                    .addComponent(addressTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(town)
                    .addComponent(townTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinces)
                    .addComponent(provinceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCode)
                    .addComponent(postalCodeTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landMark)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(submit)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextboxActionPerformed

    private void dateOfBirthTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfBirthTextboxActionPerformed

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioActionPerformed

    private void maritalStatusTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maritalStatusTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maritalStatusTextboxActionPerformed

    private void addressTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextboxActionPerformed

    private void townTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_townTextboxActionPerformed

    private void postalCodeTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalCodeTextboxActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String first = firstNameTextbox.getText();
        String last = lastNameTextbox.getText();
        String age = dateOfBirthTextbox.getText();
        String email = emailTextbox.getText();
        String status = (String) workStatusTextbox.getSelectedItem();
        String genders = genderButtonGroup.getSelection().getActionCommand();
        System.out.println("+first+" );
        
     
    }//GEN-LAST:event_submitActionPerformed

    private void emailTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressTextbox;
    private javax.swing.JLabel contactInformation;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JTextField dateOfBirthTextbox;
    private javax.swing.JTextField emailTextbox;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameTextbox;
    private javax.swing.JLabel gender;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel landMark;
    private javax.swing.JTextArea landMarkTextbox;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameTextbox;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JLabel maritalStatus;
    private javax.swing.JComboBox<String> maritalStatusTextbox;
    private javax.swing.JRadioButton othersRadio;
    private javax.swing.JLabel postalCode;
    private javax.swing.JTextField postalCodeTextbox;
    private javax.swing.JComboBox<String> provinceComboBox;
    private javax.swing.JLabel provinces;
    private javax.swing.JLabel provinces1;
    private javax.swing.JButton submit;
    private javax.swing.JLabel titleLable;
    private javax.swing.JLabel town;
    private javax.swing.JTextField townTextbox;
    private javax.swing.JLabel workStatus;
    private javax.swing.JComboBox<String> workStatusTextbox;
    // End of variables declaration//GEN-END:variables
}
